services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: db
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: "27017"
    depends_on:
      - mongo
  counterstorage:
    image: redis
    volumes:
      - ./data:/data 
  counterapp:
    image: ollatair/counterapp:v1.0.0
    ports: 
      - 3002:3002
    environment:
      - PORTS=3002
      - REDIS_URL=redis://counterstorage
    depends_on:
      - counterstorage 
  bookapp:
    image: ollatair/book:v1.0.0
    ports: 
      - 3000:3000
    environment:
      - PORTS=3000
      - CNT_PORT=3002
      - REDIS_URL=redis://counterstorage
    depends_on:
      - counterapp