version: "3"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: db
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: "27017"
    depends_on:
      - mongo
  counterstorage:
    image: redis
    volumes:
      - ./data:/data 
  counterapp:
    build: ./counterapp
    restart: always
    ports: 
      - 3002:3002
    environment:
      - PORTS=3002
      - REDIS_URL=redis://counterstorage
    volumes:
      - /app/node_modules
      - ./counterapp:/app
    depends_on:
      - counterstorage 
  bookapp:
    build: ./bookapp
    command: npm run dev
    restart: always
    ports: 
      - 3000:3000
    environment:
      - PORTS=3000
      - CNT_PORT=3002
      - REDIS_URL=redis://counterstorage
    volumes:
      - /app/node_modules
      - ./bookapp:/app
    depends_on:
      - counterapp